### ISSUE TITLE
[@resolid/remix-plugins/node-hono] Feature: Custom Hono server

### ISSUE THREAD

**Issue by 2dragonly** [huijiewei/resolid#2]
I finally able to use Hono on vercel, it's only work when using `@resolid/remix-plugins/node-hono` 😭 

can you add feature on Hono preset to be able to add custom hono server?
I want to be able to add/use a middleware on Hono server, because `remix.handler.ts` can't do much, It can only use context..

**Comment by 2dragonly** [comment]
Also, Hono preset only works on `vite:build`, the hono server doesn't run on `vite:dev`..
If I use `@hono/vite-dev-server` with custom hono server it runs, but it's just in development. 
Because, resolid hono preset have own server setup with `remix.handler.ts` 😢 
It will not overwrite the resolid hono server with my custom server.

**Comment by huijiewei** [comment]
Resolid just uses hono as a forwarder. There is no plan to customize hono for now. Thank you for your feedback. I am also waiting for remix to support middleware.

**Comment by huijiewei** [comment]
https://github.com/huijiewei/react-router-hono-vercel-demo

I will merge react-router-plugins to this project.

**Comment by huijiewei** [comment]
You can use v3 version of https://github.com/huijiewei/resolid-remix-plugins

vercel template is also updated
https://github.com/huijiewei/remix-vite-vercel-template
